[schema]
url = "https://iam-db-runtime-675766508318.asia-south1.run.app"
lang = "Rust"
orm = "Diesel"
root = "src/models"
schema_id = "4b14a9a6-9445-448b-9fc7-3cf5a1336bc6"
cache_schema_id = "7fe18d54-8732-4b53-90d7-8feb65ab61b0"
branch = "main"

[tables]
names = ["user", "app", "group", "api_token"]
