[schema]
url = "https://iam-db-runtime-675766508318.asia-south1.run.app"
lang = "Rust"
orm = "Diesel"
root = "src/models"
schema_id = "0fdaf4b4-380b-460b-a9e1-b150d8f8f046"
cache_schema_id = "7fe18d54-8732-4b53-90d7-8feb65ab61b0"
branch = "main"

[tables]
names = ["user", "app", "group", "api_token"]
