[schema]
branch = "main"
lang = "Rust"
orm = "Diesel"
root = "src/models"
schema_id = "a56e44a9-cfc6-4f69-9b7f-510789b6fa80"
url = "http://localhost:9002"

[tables]
names = ["user", "token", "app", "group"]
